name: Continuos Delivery

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

env:
    VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
    VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
    VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

on: 
    pull_request:
        branches: ['main']

jobs:
    deploy-vercel:
        permissions: 
          pull-requests: write 
        runs-on: ubuntu-latest
        steps:
            - name: Baixar repos
              uses: actions/checkout@v3
            - name: Versão Nodejs
              uses: actions/setup-node@v2
              with:
                node-version: 18.12.0
                uses: actions/checkout@v2
        
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
            - name: Build Project Artifacts
              run: vercel build --prod --token=$VERCEL_TOKEN
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

